
import {repo} from './database.js';
import {uid,esc,fmtDate,avg,pct,today} from './utils.js';
import {ATTENDANCE,evaluationMean} from './evaluations.js';
import {playerStats} from './players.js';
import {calcularMinutosJugador,jugadoresEnCampo} from './participation.js';
import {resultForTeam,rival} from './matches.js';
import {teamEval} from './statistics.js';
import {exportBackup,importBackup} from './backup.js';

const A=document.querySelector('#app'), title=document.querySelector('#pageTitle'), subtitle=document.querySelector('#pageSubtitle');
const modalEl=document.querySelector('#appModal'), modal=new bootstrap.Modal(modalEl), toastEl=document.querySelector('#appToast'), toast=new bootstrap.Toast(toastEl,{delay:1800});
let charts=[];
const nav=[['dashboard','fa-gauge','Dashboard'],['calendar','fa-calendar','Calendario'],['trainings','fa-person-running','Entrenamientos'],['matches','fa-trophy','Partidos'],['players','fa-users','Jugadores'],['compare','fa-code-compare','Comparar jugadores'],['stats','fa-chart-line','Estadísticas'],['config','fa-gear','Configuración'],['backup','fa-database','Copia de seguridad']];
document.querySelector('#mainNav').innerHTML=nav.map(x=>`<a href="#${x[0]}" class="nav-link-app" data-route="${x[0]}"><i class="fa-solid ${x[1]}"></i>${x[2]}</a>`).join('');
document.querySelector('#menuBtn').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');
window.addEventListener('hashchange',route); window.addEventListener('DOMContentLoaded',init);
function notify(s){toastEl.querySelector('.toast-body').textContent=s;toast.show()}
function saved(){const b=document.querySelector('#saveBadge');b.classList.add('show');setTimeout(()=>b.classList.remove('show'),900)}
function cleanCharts(){charts.forEach(c=>c.destroy());charts=[]}
function setHead(t,s=''){title.textContent=t;subtitle.textContent=s;document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',location.hash===`#${a.dataset.route}`))}
function openModal(t,body,footer=''){modalEl.querySelector('.modal-title').textContent=t;modalEl.querySelector('.modal-body').innerHTML=body;modalEl.querySelector('.modal-footer').innerHTML=footer;modal.show()}
async function init(){if(!(await repo.get('config','main'))){await loadDemo()}location.hash=location.hash||'#dashboard';route()}
async function loadDemo(){const d=await fetch('data/demo-data.json').then(r=>r.json());await repo.replaceAll(d)}
async function route(){cleanCharts();document.querySelector('#sidebar').classList.remove('open');const r=(location.hash.slice(1)||'dashboard').split('/');const fn={dashboard,calendar,trainings,matches,players,compare,stats,config,backup,trainingDetail,matchDetail,playerDetail,quickTraining,liveMatch}[r[0]]||dashboard;await fn(r[1])}
async function cfg(){return await repo.get('config','main')||{}}
function statCard(icon,label,val){return `<div class="col-6 col-xl-3"><div class="card stat-card h-100"><div class="card-body d-flex gap-3 align-items-center"><div class="icon"><i class="fa-solid ${icon}"></i></div><div><div class="small text-secondary">${label}</div><div class="stat-value">${val}</div></div></div></div></div>`}
async function dashboard(){
 setHead('Dashboard','Resumen de la temporada');const [c,ps,ts,es,ms]=await Promise.all([cfg(),repo.all('players'),repo.all('trainings'),repo.all('evaluations'),repo.all('matches')]);brand(c);
 const ev=teamEval(es),att=es.length?pct(es.filter(e=>['presente','tarde'].includes(e.asistencia)).length,es.length):0, played=ms.filter(m=>m.estado==='disputado');
 const res=played.map(resultForTeam), nextT=ts.filter(t=>t.fecha>=today()).sort((a,b)=>a.fecha.localeCompare(b.fecha))[0],nextM=ms.filter(m=>m.fecha>=today()&&m.estado==='planificado').sort((a,b)=>a.fecha.localeCompare(b.fecha))[0];
 A.innerHTML=`<div class="row g-3 mb-4">${statCard('fa-users','Jugadores activos',ps.filter(p=>p.activo).length)}${statCard('fa-person-running','Entrenamientos',ts.filter(t=>t.estado==='realizado').length)}${statCard('fa-user-check','Asistencia media',att.toFixed(1)+'%')}${statCard('fa-star','Valoración media',ev.global?.toFixed(2)||'—')}${statCard('fa-trophy','Partidos jugados',played.length)}${statCard('fa-medal','Victorias',res.filter(x=>x==='Victoria').length)}${statCard('fa-equals','Empates',res.filter(x=>x==='Empate').length)}${statCard('fa-flag','Derrotas',res.filter(x=>x==='Derrota').length)}</div>
 <div class="row g-3"><div class="col-lg-7"><div class="card"><div class="card-body"><div class="section-title">Evolución del equipo</div><canvas id="teamChart" height="110"></canvas></div></div></div><div class="col-lg-5"><div class="card mb-3"><div class="card-body"><b>Próximo entrenamiento</b><div class="mt-2">${nextT?fmtDate(nextT.fecha)+' · '+esc(nextT.horaInicio)+' · '+esc(nextT.tipo):'Sin entrenamientos próximos'}</div></div></div><div class="card"><div class="card-body"><b>Próximo partido</b><div class="mt-2">${nextM?fmtDate(nextM.fecha)+' · vs '+esc(rival(nextM)):'Sin partidos próximos'}</div><hr><b>Último resultado</b><div>${played.length?esc(rival(played.at(-1)))+' · '+played.at(-1).golesLocal+'-'+played.at(-1).golesVisitante:'—'}</div></div></div></div></div>`;
 const done=ts.filter(t=>t.estado==='realizado').sort((a,b)=>a.fecha.localeCompare(b.fecha));charts.push(new Chart(document.querySelector('#teamChart'),{type:'line',data:{labels:done.map(t=>fmtDate(t.fecha)),datasets:[{label:'Valoración',data:done.map(t=>avg(es.filter(e=>e.trainingId===t.id).map(e=>evaluationMean(e))))},{label:'Asistencia %',data:done.map(t=>{const x=es.filter(e=>e.trainingId===t.id);return pct(x.filter(e=>['presente','tarde'].includes(e.asistencia)).length,x.length)/20})}]},options:{responsive:true,interaction:{mode:'index'}}}));
}
function brand(c){document.querySelector('#brandTeam').textContent=c.team||'Mi Equipo';document.querySelector('#brandSeason').textContent=c.season||'Temporada'}
async function players(){
 setHead('Jugadores','Plantilla de la temporada');const ps=await repo.all('players');
 A.innerHTML=`<div class="d-flex justify-content-between mb-3"><div class="btn-group"><button class="btn btn-outline-secondary" id="onlyActive">Activos</button><button class="btn btn-outline-secondary" id="allPlayers">Todos</button></div><button class="btn btn-primary" id="newPlayer"><i class="fa-solid fa-plus"></i> Nuevo jugador</button></div><div id="playersTable"></div>`;
 const draw=(all=false)=>document.querySelector('#playersTable').innerHTML=`<div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Dorsal</th><th>Jugador</th><th>Posición</th><th>Estado</th><th></th></tr></thead><tbody>${ps.filter(p=>all||p.activo).sort((a,b)=>a.dorsal-b.dorsal).map(p=>`<tr><td><b>${p.dorsal}</b></td><td>${esc(p.nombre)} ${esc(p.apellidos)}</td><td>${esc(p.posicion)}</td><td><span class="badge text-bg-${p.activo?'success':'secondary'}">${p.activo?'Activo':'Baja'}</span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="#playerDetail/${p.id}">Ficha</a> <button class="btn btn-sm btn-outline-secondary edit-player" data-id="${p.id}">Editar</button></td></tr>`).join('')}</tbody></table></div></div>`;draw();
 document.querySelector('#onlyActive').onclick=()=>draw(false);document.querySelector('#allPlayers').onclick=()=>draw(true);document.querySelector('#newPlayer').onclick=()=>playerForm();A.onclick=e=>{const b=e.target.closest('.edit-player');if(b)playerForm(ps.find(p=>p.id===b.dataset.id))}
}
async function playerForm(p={}){
 const c=await cfg(), body=`<form id="playerForm" class="row g-3"><input type="hidden" name="id" value="${p.id||''}"><div class="col-md-6"><label class="form-label">Nombre</label><input required class="form-control" name="nombre" value="${esc(p.nombre||'')}"></div><div class="col-md-6"><label class="form-label">Apellidos</label><input required class="form-control" name="apellidos" value="${esc(p.apellidos||'')}"></div><div class="col-4"><label class="form-label">Dorsal</label><input required type="number" class="form-control" name="dorsal" value="${p.dorsal||''}"></div><div class="col-8"><label class="form-label">Posición</label><select class="form-select" name="posicion">${(c.positions||[]).map(x=>`<option ${x===p.posicion?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="col-md-6"><label class="form-label">Nacimiento</label><input type="date" class="form-control" name="nacimiento" value="${p.nacimiento||''}"></div><div class="col-md-6"><label class="form-label">Fecha alta</label><input type="date" class="form-control" name="fechaAlta" value="${p.fechaAlta||today()}"></div><div class="col-12"><label class="form-label">Observaciones</label><textarea class="form-control" name="observaciones">${esc(p.observaciones||'')}</textarea></div><div class="col-12 form-check ms-2"><input class="form-check-input" type="checkbox" name="activo" ${p.activo!==false?'checked':''}><label class="form-check-label">Jugador activo</label></div></form>`;
 openModal(p.id?'Editar jugador':'Nuevo jugador',body,`<button class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary" id="savePlayer">Guardar</button>`);
 document.querySelector('#savePlayer').onclick=async()=>{const f=document.querySelector('#playerForm');if(!f.reportValidity())return;const d=Object.fromEntries(new FormData(f));await repo.put('players',{...p,...d,id:p.id||uid('J'),dorsal:+d.dorsal,activo:f.activo.checked});modal.hide();notify('Jugador guardado');players()}
}
async function trainings(){
 setHead('Entrenamientos','Planificación e histórico');const ts=(await repo.all('trainings')).sort((a,b)=>b.fecha.localeCompare(a.fecha));
 A.innerHTML=`<div class="d-flex justify-content-end mb-3"><button class="btn btn-primary" id="newTraining"><i class="fa-solid fa-plus"></i> Nuevo entrenamiento</button></div><div class="card"><div class="table-responsive"><table class="table mb-0 align-middle"><thead><tr><th>Fecha</th><th>Tipo</th><th>Lugar</th><th>Estado</th><th></th></tr></thead><tbody>${ts.map(t=>`<tr><td>${fmtDate(t.fecha)} ${esc(t.horaInicio)}</td><td>${esc(t.tipo)}</td><td>${esc(t.lugar)}</td><td>${esc(t.estado)}</td><td class="text-end"><a class="btn btn-sm btn-primary" href="#trainingDetail/${t.id}">Abrir</a> <a class="btn btn-sm btn-outline-success" href="#quickTraining/${t.id}">Rápido</a></td></tr>`).join('')}</tbody></table></div></div>`;document.querySelector('#newTraining').onclick=()=>trainingForm();
}
async function trainingForm(t={}){
 const c=await cfg();openModal('Entrenamiento',`<form id="tf" class="row g-3"><div class="col-md-4"><label class="form-label">Fecha</label><input required type="date" name="fecha" class="form-control" value="${t.fecha||today()}"></div><div class="col-md-4"><label class="form-label">Inicio</label><input type="time" name="horaInicio" class="form-control" value="${t.horaInicio||'18:00'}"></div><div class="col-md-4"><label class="form-label">Final</label><input type="time" name="horaFin" class="form-control" value="${t.horaFin||'19:30'}"></div><div class="col-md-6"><label class="form-label">Tipo</label><select name="tipo" class="form-select">${(c.trainingTypes||[]).map(x=>`<option>${esc(x)}</option>`)}</select></div><div class="col-md-6"><label class="form-label">Lugar</label><input name="lugar" class="form-control" value="${esc(t.lugar||'')}"></div><div class="col-12"><label class="form-label">Objetivos</label><textarea name="objetivos" class="form-control">${esc(t.objetivos||'')}</textarea></div><div class="col-12"><label class="form-label">Contenido</label><textarea name="contenido" class="form-control">${esc(t.contenido||'')}</textarea></div><div class="col-md-6"><label class="form-label">Estado</label><select name="estado" class="form-select"><option>planificado</option><option>realizado</option><option>cancelado</option></select></div></form>`,`<button class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary" id="saveT">Guardar</button>`);
 document.querySelector('#saveT').onclick=async()=>{const f=document.querySelector('#tf');if(!f.reportValidity())return;await repo.put('trainings',{...t,...Object.fromEntries(new FormData(f)),id:t.id||uid('E'),observaciones:t.observaciones||''});modal.hide();trainings()}
}
async function trainingDetail(id){const t=await repo.get('trainings',id);if(!t)return trainings();setHead('Ficha de entrenamiento',fmtDate(t.fecha));A.innerHTML=`<div class="card mb-3"><div class="card-body"><div class="d-flex justify-content-between"><div><h4>${esc(t.tipo)} · ${fmtDate(t.fecha)}</h4><div>${esc(t.horaInicio)}–${esc(t.horaFin)} · ${esc(t.lugar)}</div></div><div class="no-print"><a href="#quickTraining/${id}" class="btn btn-success">Modo rápido</a> <button onclick="print()" class="btn btn-outline-secondary">Imprimir</button></div></div><hr><b>Objetivos</b><p>${esc(t.objetivos)}</p><b>Contenido</b><p>${esc(t.contenido)}</p></div></div><div class="card"><div class="card-body"><div class="section-title">Control de jugadores</div><div id="evalTable"></div></div></div>`;await renderEvalTable(id)}
async function renderEvalTable(id){const [ps,es]=await Promise.all([repo.all('players'),repo.all('evaluations')]);const ev=es.filter(e=>e.trainingId===id);document.querySelector('#evalTable').innerHTML=`<div class="table-responsive"><table class="table"><thead><tr><th>Jugador</th><th>Asistencia</th><th>Comp.</th><th>Act.</th><th>Efic.</th><th>Media</th><th>Observaciones</th></tr></thead><tbody>${ps.filter(p=>p.activo).map(p=>{const e=ev.find(x=>x.playerId===p.id)||{};return `<tr><td>${p.dorsal} · ${esc(p.nombre)} ${esc(p.apellidos)}</td><td>${esc(e.asistencia||'—')}</td><td>${e.comportamiento??'—'}</td><td>${e.actitud??'—'}</td><td>${e.eficacia??'—'}</td><td>${evaluationMean(e)?.toFixed(2)||'—'}</td><td>${esc(e.observaciones||'')}</td></tr>`}).join('')}</tbody></table></div>`}
async function quickTraining(id){const [t,ps,es]=await Promise.all([repo.get('trainings',id),repo.all('players'),repo.all('evaluations')]);setHead('Entrenamiento rápido',t?`${fmtDate(t.fecha)} · ${t.horaInicio}`:'');const ev=es.filter(e=>e.trainingId===id);A.innerHTML=`<div class="d-flex justify-content-between mb-3"><a href="#trainingDetail/${id}" class="btn btn-outline-secondary">Ficha</a><button id="allPresent" class="btn btn-success">Marcar todos presentes</button></div><div id="quickList" class="row g-3">${ps.filter(p=>p.activo).map(p=>quickCard(p,ev.find(x=>x.playerId===p.id)||{})).join('')}</div>`;A.onchange=A.onclick=async e=>{const card=e.target.closest('[data-player]');if(!card)return;if(e.target.matches('[data-att]')){card.querySelectorAll('[data-att]').forEach(b=>b.classList.remove('active'));e.target.classList.add('active')}if(e.target.matches('.rate-btn')){const group=e.target.dataset.metric;card.querySelectorAll(`[data-metric="${group}"]`).forEach(b=>b.classList.toggle('active',+b.dataset.value<=+e.target.dataset.value))}if(e.target.matches('button,input,textarea'))await saveQuick(card,id)};document.querySelector('#allPresent').onclick=async()=>{for(const card of document.querySelectorAll('[data-player]')){card.querySelectorAll('[data-att]').forEach(b=>b.classList.toggle('active',b.dataset.att==='presente'));await saveQuick(card,id)}}
}
function quickCard(p,e){const rating=m=>`<div class="rating">${[1,2,3,4,5].map(n=>`<button class="rate-btn ${n<=(e[m]||0)?'active':''}" data-metric="${m}" data-value="${n}">${n}</button>`).join('')}</div>`;return `<div class="col-12 col-xl-6"><div class="card player-quick" data-player="${p.id}"><div class="card-body"><h5>${p.dorsal} · ${esc(p.nombre)} ${esc(p.apellidos)}</h5><div class="small fw-bold mt-3">ASISTENCIA</div><div class="attendance-pills my-2">${ATTENDANCE.map(([v,l])=>`<button class="btn btn-sm btn-outline-primary ${e.asistencia===v?'active':''}" data-att="${v}">${l}</button>`).join('')}</div><div class="row g-2 mt-2"><div class="col-sm-4"><small>Comportamiento</small>${rating('comportamiento')}</div><div class="col-sm-4"><small>Actitud</small>${rating('actitud')}</div><div class="col-sm-4"><small>Eficacia</small>${rating('eficacia')}</div></div><textarea class="form-control mt-3" rows="2" placeholder="Observaciones">${esc(e.observaciones||'')}</textarea></div></div></div>`}
async function saveQuick(card,tid){const get=m=>{const a=[...card.querySelectorAll(`[data-metric="${m}"].active`)];return a.length?+a.at(-1).dataset.value:null};await repo.put('evaluations',{id:`EV_${tid}_${card.dataset.player}`,trainingId:tid,playerId:card.dataset.player,asistencia:card.querySelector('[data-att].active')?.dataset.att||'',comportamiento:get('comportamiento'),actitud:get('actitud'),eficacia:get('eficacia'),observaciones:card.querySelector('textarea').value});saved()}
async function matches(){setHead('Partidos','Competición y participación');const ms=(await repo.all('matches')).sort((a,b)=>b.fecha.localeCompare(a.fecha));A.innerHTML=`<div class="d-flex justify-content-end mb-3"><button class="btn btn-primary" id="newMatch"><i class="fa-solid fa-plus"></i> Nuevo partido</button></div><div class="card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Fecha</th><th>Jornada</th><th>Rival</th><th>L/V</th><th>Resultado</th><th>Estado</th><th></th></tr></thead><tbody>${ms.map(m=>`<tr><td>${fmtDate(m.fecha)}</td><td>${m.jornada||'—'}</td><td>${esc(rival(m))}</td><td>${m.somosLocal?'Local':'Visitante'}</td><td>${m.golesLocal??'—'} - ${m.golesVisitante??'—'} <small>${resultForTeam(m)}</small></td><td>${esc(m.estado)}</td><td><a class="btn btn-sm btn-primary" href="#matchDetail/${m.id}">Abrir</a> <a class="btn btn-sm btn-outline-success" href="#liveMatch/${m.id}">Modo partido</a></td></tr>`).join('')}</tbody></table></div></div>`;document.querySelector('#newMatch').onclick=()=>matchForm()}
async function matchForm(m={}){const c=await cfg();openModal('Partido',`<form id="mf" class="row g-3"><div class="col-md-4"><label class="form-label">Fecha</label><input required type="date" name="fecha" class="form-control" value="${m.fecha||today()}"></div><div class="col-md-4"><label class="form-label">Hora</label><input type="time" name="hora" class="form-control" value="${m.hora||'11:30'}"></div><div class="col-md-4"><label class="form-label">Jornada</label><input type="number" name="jornada" class="form-control" value="${m.jornada||''}"></div><div class="col-md-6"><label class="form-label">Competición</label><input name="competicion" class="form-control" value="${esc(m.competicion||'Liga')}"></div><div class="col-md-6"><label class="form-label">Lugar</label><input name="lugar" class="form-control" value="${esc(m.lugar||'')}"></div><div class="col-md-6"><label class="form-label">Equipo local</label><input required name="equipoLocal" class="form-control" value="${esc(m.equipoLocal||c.team||'')}"></div><div class="col-md-6"><label class="form-label">Equipo visitante</label><input required name="equipoVisitante" class="form-control" value="${esc(m.equipoVisitante||'')}"></div><div class="col-md-4"><label class="form-label">Duración</label><input type="number" name="duracion" class="form-control" value="${m.duracion||c.defaultMatchDuration||90}"></div><div class="col-md-4"><label class="form-label">Goles local</label><input type="number" name="golesLocal" class="form-control" value="${m.golesLocal??''}"></div><div class="col-md-4"><label class="form-label">Goles visitante</label><input type="number" name="golesVisitante" class="form-control" value="${m.golesVisitante??''}"></div><div class="col-md-6"><label class="form-label">Estado</label><select name="estado" class="form-select"><option>planificado</option><option>disputado</option><option>suspendido</option><option>cancelado</option></select></div><div class="col-md-6 form-check mt-5 ms-2"><input class="form-check-input" type="checkbox" name="somosLocal" ${m.somosLocal!==false?'checked':''}><label class="form-check-label">Nuestro equipo es local</label></div></form>`,`<button class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary" id="saveM">Guardar</button>`);document.querySelector('#saveM').onclick=async()=>{const f=document.querySelector('#mf');if(!f.reportValidity())return;const d=Object.fromEntries(new FormData(f));await repo.put('matches',{...m,...d,id:m.id||uid('P'),jornada:+d.jornada||null,duracion:+d.duracion,golesLocal:d.golesLocal===''?null:+d.golesLocal,golesVisitante:d.golesVisitante===''?null:+d.golesVisitante,somosLocal:f.somosLocal.checked,observaciones:m.observaciones||''});modal.hide();matches()}}
async function matchDetail(id){const [m,ps,cs,xs,c]=await Promise.all([repo.get('matches',id),repo.all('players'),repo.all('callups'),repo.all('changes'),cfg()]);if(!m)return matches();setHead('Ficha de partido',`${fmtDate(m.fecha)} · ${m.competicion}`);const call=cs.filter(x=>x.matchId===id),changes=xs.filter(x=>x.matchId===id).sort((a,b)=>a.minuto-b.minuto);let rows='';for(const p of ps.filter(p=>p.activo)){const ca=call.find(x=>x.playerId===p.id);const min=await calcularMinutosJugador(id,p.id);rows+=`<tr><td>${p.dorsal} · ${esc(p.nombre)} ${esc(p.apellidos)}</td><td><select class="form-select form-select-sm callup" data-player="${p.id}">${['titular','suplente','noConvocado','lesionado','noDisponible'].map(x=>`<option ${ca?.situacionInicial===x?'selected':''}>${x}</option>`).join('')}</select></td><td>${min} min</td></tr>`}
 A.innerHTML=`<div class="card mb-3"><div class="card-body"><div class="d-flex justify-content-between"><div><div class="text-secondary">${fmtDate(m.fecha)} · Jornada ${m.jornada||'—'}</div><div class="match-score">${esc(m.equipoLocal)} ${m.golesLocal??'–'} - ${m.golesVisitante??'–'} ${esc(m.equipoVisitante)}</div><div>${resultForTeam(m)} · ${m.duracion} min</div></div><div class="no-print"><a class="btn btn-success" href="#liveMatch/${id}">Modo partido</a><button class="btn btn-outline-secondary ms-1" id="editMatch">Editar</button></div></div></div></div><div class="row g-3"><div class="col-lg-7"><div class="card"><div class="card-body"><div class="section-title">Convocatoria y alineación <small class="text-secondary">(titulares configurados: ${c.starters||11})</small></div><div class="table-responsive"><table class="table"><thead><tr><th>Jugador</th><th>Situación</th><th>Minutos</th></tr></thead><tbody>${rows}</tbody></table></div></div></div></div><div class="col-lg-5"><div class="card"><div class="card-body"><div class="d-flex justify-content-between"><div class="section-title">Cambios</div><button class="btn btn-sm btn-primary" id="addChange">+ Registrar cambio</button></div><div>${changes.length?changes.map(x=>{const a=ps.find(p=>p.id===x.jugadorSaleId),b=ps.find(p=>p.id===x.jugadorEntraId);return `<div class="py-2 border-bottom"><b>${x.minuto}'</b> — Sale ${esc(a?.nombre||'')} / Entra ${esc(b?.nombre||'')}</div>`}).join(''):'Sin cambios registrados'}</div></div></div></div></div>`;
 document.querySelector('#editMatch').onclick=()=>matchForm(m);document.querySelectorAll('.callup').forEach(s=>s.onchange=async()=>{const old=call.find(x=>x.playerId===s.dataset.player);await repo.put('callups',{id:old?.id||uid('C'),matchId:id,playerId:s.dataset.player,convocado:['titular','suplente'].includes(s.value),situacionInicial:s.value});saved();matchDetail(id)});document.querySelector('#addChange').onclick=()=>changeForm(id,ps,m)}
function changeForm(id,ps,m){openModal('Registrar cambio',`<form id="cf" class="row g-3"><div class="col-4"><label class="form-label">Minuto</label><input required type="number" min="0" max="${m.duracion}" name="minuto" class="form-control"></div><div class="col-8"></div><div class="col-md-6"><label class="form-label">Sale</label><select name="jugadorSaleId" class="form-select">${ps.filter(p=>p.activo).map(p=>`<option value="${p.id}">${p.dorsal} · ${esc(p.nombre)} ${esc(p.apellidos)}</option>`)}</select></div><div class="col-md-6"><label class="form-label">Entra</label><select name="jugadorEntraId" class="form-select">${ps.filter(p=>p.activo).map(p=>`<option value="${p.id}">${p.dorsal} · ${esc(p.nombre)} ${esc(p.apellidos)}</option>`)}</select></div><div class="col-12"><label class="form-label">Observaciones</label><input name="observaciones" class="form-control"></div></form>`,`<button class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary" id="saveC">Guardar cambio</button>`);document.querySelector('#saveC').onclick=async()=>{const f=document.querySelector('#cf'),d=Object.fromEntries(new FormData(f));if(d.jugadorSaleId===d.jugadorEntraId)return notify('Selecciona jugadores diferentes');await repo.put('changes',{...d,id:uid('X'),matchId:id,minuto:+d.minuto});modal.hide();saved();matchDetail(id)}}
async function liveMatch(id){const [m,ps,xs]=await Promise.all([repo.get('matches',id),repo.all('players'),repo.all('changes')]);setHead('Modo partido',`${m.equipoLocal} ${m.golesLocal??0} - ${m.golesVisitante??0} ${m.equipoVisitante}`);const current=await jugadoresEnCampo(id,m.duracion);let cards='';for(const pid of current){const p=ps.find(x=>x.id===pid);cards+=`<div class="player-chip onfield"><b>${p?.dorsal} · ${esc(p?.nombre||'')}</b><div>${await calcularMinutosJugador(id,pid)} min calculados</div></div>`}A.innerHTML=`<div class="card mb-3"><div class="card-body"><div class="match-score">${esc(m.equipoLocal)} ${m.golesLocal??0} - ${m.golesVisitante??0} ${esc(m.equipoVisitante)}</div><div>${m.duracion} minutos reglamentarios</div></div></div><div class="card"><div class="card-body"><div class="d-flex justify-content-between"><div class="section-title">Jugadores en campo</div><button class="btn btn-primary" id="liveChange">CAMBIO</button></div><div class="field-list">${cards}</div><hr><div class="section-title">Histórico de cambios</div>${xs.filter(x=>x.matchId===id).sort((a,b)=>a.minuto-b.minuto).map(x=>`<div>${x.minuto}' · ${esc(ps.find(p=>p.id===x.jugadorSaleId)?.nombre||'')} → ${esc(ps.find(p=>p.id===x.jugadorEntraId)?.nombre||'')}</div>`).join('')}</div></div>`;document.querySelector('#liveChange').onclick=()=>changeForm(id,ps,m)}
async function playerDetail(id){const [p,s,es,ts,ms]=await Promise.all([repo.get('players',id),playerStats(id),repo.all('evaluations'),repo.all('trainings'),repo.all('matches')]);setHead('Ficha del jugador',`${p.dorsal} · ${p.nombre} ${p.apellidos}`);const ev=es.filter(e=>e.playerId===id).sort((a,b)=>(ts.find(t=>t.id===a.trainingId)?.fecha||'').localeCompare(ts.find(t=>t.id===b.trainingId)?.fecha||''));A.innerHTML=`<div class="row g-3 mb-3">${statCard('fa-user-check','Asistencia',s.attendancePct.toFixed(1)+'%')}${statCard('fa-star','Valoración',s.global?.toFixed(2)||'—')}${statCard('fa-trophy','Partidos',s.matchesPlayed)}${statCard('fa-clock','Minutos',s.totalMinutes)}</div><div class="card mb-3"><div class="card-body"><div class="d-flex justify-content-between"><div><h4>${p.dorsal} · ${esc(p.nombre)} ${esc(p.apellidos)}</h4><div>${esc(p.posicion)} · ${p.activo?'Activo':'Baja'}</div></div><button onclick="print()" class="btn btn-outline-secondary no-print">Imprimir</button></div><hr><div class="row"><div class="col-md-6"><b>Entrenamientos</b><p>Asistencias: ${s.attendance} · Justificadas: ${s.just} · No justificadas: ${s.unJust} · Tardes: ${s.late}</p></div><div class="col-md-6"><b>Partidos</b><p>Convocatorias: ${s.callups} · Titularidades: ${s.starters} · Entradas: ${s.entered} · ${s.pctMinutes.toFixed(1)}% minutos disponibles</p></div></div></div></div><div class="card"><div class="card-body"><div class="section-title">Evolución</div><canvas id="playerChart" height="100"></canvas></div></div>`;
 charts.push(new Chart(document.querySelector('#playerChart'),{type:'line',data:{labels:ev.map(e=>fmtDate(ts.find(t=>t.id===e.trainingId)?.fecha)),datasets:[{label:'Comportamiento',data:ev.map(e=>e.comportamiento)},{label:'Actitud',data:ev.map(e=>e.actitud)},{label:'Eficacia',data:ev.map(e=>e.eficacia)}]},options:{scales:{y:{min:1,max:5}}}}))}
async function compare(){setHead('Comparar jugadores','Comparativa objetiva de 2 a 4 jugadores');const ps=(await repo.all('players')).filter(p=>p.activo);A.innerHTML=`<div class="card mb-3"><div class="card-body"><label class="form-label">Selecciona entre 2 y 4 jugadores</label><div class="row g-2">${[0,1,2,3].map((_,i)=>`<div class="col-md-3"><select class="form-select cmp"><option value="">Jugador ${i+1}</option>${ps.map(p=>`<option value="${p.id}">${p.dorsal} · ${esc(p.nombre)} ${esc(p.apellidos)}</option>`)}</select></div>`).join('')}</div><button class="btn btn-primary mt-3" id="doCompare">Comparar</button></div></div><div id="cmpOut"></div>`;document.querySelector('#doCompare').onclick=async()=>{const ids=[...document.querySelectorAll('.cmp')].map(x=>x.value).filter(Boolean);if(ids.length<2)return notify('Selecciona al menos 2 jugadores');const ss=[];for(const id of ids)ss.push({p:ps.find(x=>x.id===id),s:await playerStats(id)});const metrics=[['Asistencia %','attendancePct'],['Comportamiento','behavior'],['Actitud','attitude'],['Eficacia','efficacy'],['Valoración','global'],['Convocatorias','callups'],['Partidos jugados','matchesPlayed'],['Titularidades','starters'],['Minutos jugados','totalMinutes'],['Media min/partido','avgMinutes'],['% minutos','pctMinutes'],['Veces sustituido','substituted'],['Entradas banquillo','entered']];document.querySelector('#cmpOut').innerHTML=`<div class="card"><div class="table-responsive"><table class="table compare-table"><thead><tr><th>Métrica</th>${ss.map(x=>`<th>${esc(x.p.nombre)} ${esc(x.p.apellidos)}</th>`).join('')}</tr></thead><tbody>${metrics.map(([l,k])=>`<tr><td>${l}</td>${ss.map(x=>`<td>${Number.isFinite(x.s[k])?x.s[k].toFixed(k.includes('Pct')||k==='pctMinutes'?1:2):'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`}}
async function stats(){setHead('Estadísticas','Visión global del equipo');const [ps,es]=await Promise.all([repo.all('players'),repo.all('evaluations')]);const ev=teamEval(es);A.innerHTML=`<div class="row g-3">${statCard('fa-user-check','Registros asistencia',es.length)}${statCard('fa-face-smile','Comportamiento',ev.behavior?.toFixed(2)||'—')}${statCard('fa-bolt','Actitud',ev.attitude?.toFixed(2)||'—')}${statCard('fa-bullseye','Eficacia',ev.efficacy?.toFixed(2)||'—')}</div><div class="card mt-3"><div class="card-body"><canvas id="attChart" height="100"></canvas></div></div>`;const vals=[];for(const p of ps.filter(x=>x.activo)){const x=es.filter(e=>e.playerId===p.id);vals.push(pct(x.filter(e=>['presente','tarde'].includes(e.asistencia)).length,x.length))}charts.push(new Chart(document.querySelector('#attChart'),{type:'bar',data:{labels:ps.filter(x=>x.activo).map(p=>p.nombre),datasets:[{label:'Asistencia %',data:vals}]},options:{scales:{y:{min:0,max:100}}}}))}
async function calendar(){setHead('Calendario','Entrenamientos y partidos');const [ts,ms]=await Promise.all([repo.all('trainings'),repo.all('matches')]);let d=new Date(),y=d.getFullYear(),mo=d.getMonth();const first=new Date(y,mo,1),start=(first.getDay()+6)%7,days=new Date(y,mo+1,0).getDate();let cells='';for(let i=0;i<start;i++)cells+=`<div class="cal-day muted"></div>`;for(let day=1;day<=days;day++){const ds=`${y}-${String(mo+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;cells+=`<div class="cal-day"><div class="cal-num">${day}</div>${ts.filter(t=>t.fecha===ds).map(t=>`<div class="event" onclick="location.hash='#trainingDetail/${t.id}'">${esc(t.tipo)}</div>`).join('')}${ms.filter(m=>m.fecha===ds).map(m=>`<div class="event match" onclick="location.hash='#matchDetail/${m.id}'">⚑ ${esc(rival(m))}</div>`).join('')}</div>`}A.innerHTML=`<div class="d-flex justify-content-between mb-3"><h4>${first.toLocaleDateString('es-ES',{month:'long',year:'numeric'})}</h4><div><button class="btn btn-outline-primary" onclick="location.hash='#trainings'">+ Entrenamiento</button> <button class="btn btn-primary" onclick="location.hash='#matches'">+ Partido</button></div></div><div class="calendar-grid">${['L','M','X','J','V','S','D'].map(x=>`<div class="cal-head">${x}</div>`).join('')}${cells}</div>`}
async function config(){setHead('Configuración','Equipo, temporada y reglas');const c=await cfg();A.innerHTML=`<div class="card"><div class="card-body"><form id="configForm" class="row g-3"><div class="col-md-6"><label class="form-label">Club</label><input class="form-control" name="club" value="${esc(c.club||'')}"></div><div class="col-md-6"><label class="form-label">Equipo</label><input class="form-control" name="team" value="${esc(c.team||'')}"></div><div class="col-md-4"><label class="form-label">Categoría</label><input class="form-control" name="category" value="${esc(c.category||'')}"></div><div class="col-md-4"><label class="form-label">Temporada</label><input class="form-control" name="season" value="${esc(c.season||'')}"></div><div class="col-md-4"><label class="form-label">Titulares iniciales</label><input type="number" class="form-control" name="starters" value="${c.starters||11}"></div><div class="col-md-6"><label class="form-label">Entrenador</label><input class="form-control" name="coach" value="${esc(c.coach||'')}"></div><div class="col-md-6"><label class="form-label">Segundo entrenador</label><input class="form-control" name="assistant" value="${esc(c.assistant||'')}"></div><div class="col-md-4"><label class="form-label">Duración partido</label><input type="number" class="form-control" name="defaultMatchDuration" value="${c.defaultMatchDuration||90}"></div><div class="col-12"><label class="form-label">Posiciones (una por línea)</label><textarea class="form-control" name="positions">${(c.positions||[]).join('\n')}</textarea></div><div class="col-12"><label class="form-label">Tipos de entrenamiento (uno por línea)</label><textarea class="form-control" name="trainingTypes">${(c.trainingTypes||[]).join('\n')}</textarea></div><div class="col-12"><button class="btn btn-primary">Guardar configuración</button> <button type="button" class="btn btn-outline-secondary" id="demoLoad">Cargar datos demo</button></div></form></div></div>`;document.querySelector('#configForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));await repo.put('config',{...c,...d,id:'main',starters:+d.starters,defaultMatchDuration:+d.defaultMatchDuration,positions:d.positions.split('\n').map(x=>x.trim()).filter(Boolean),trainingTypes:d.trainingTypes.split('\n').map(x=>x.trim()).filter(Boolean)});notify('Configuración guardada');brand(await cfg())};document.querySelector('#demoLoad').onclick=async()=>{if(confirm('Se sustituirán todos los datos. ¿Continuar?')){await loadDemo();notify('Datos demo cargados');config()}}}
async function backup(){setHead('Copia de seguridad','Exportación y restauración JSON');A.innerHTML=`<div class="row g-3"><div class="col-md-4"><div class="card h-100"><div class="card-body"><h5>Exportar datos</h5><p>Incluye configuración, jugadores, entrenamientos, evaluaciones, partidos, convocatorias y cambios.</p><button class="btn btn-primary" id="exportBtn">Exportar JSON</button></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><h5>Importar datos</h5><p>Valida la estructura antes de sustituir la información local.</p><input type="file" id="importFile" accept=".json" class="form-control"></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><h5>Restablecer</h5><p>Vacía completamente la base de datos del navegador.</p><button class="btn btn-outline-danger" id="resetBtn">Vaciar base de datos</button></div></div></div></div>`;document.querySelector('#exportBtn').onclick=exportBackup;document.querySelector('#importFile').onchange=async e=>{if(!e.target.files[0]||!confirm('La importación sustituirá todos los datos actuales. ¿Continuar?'))return;try{await importBackup(e.target.files[0]);notify('Copia restaurada');dashboard()}catch(err){notify(err.message)}};document.querySelector('#resetBtn').onclick=async()=>{if(confirm('Esta acción eliminará TODOS los datos. ¿Continuar?')){for(const s of repo.stores)await repo.clear(s);notify('Base de datos vaciada')}}}
